package manager.nodes;

import codex.model.Access;
import codex.model.Entity;
import codex.type.ArrStr;
import codex.type.EntityRef;
import codex.utils.ImageUtils;

import java.util.List;

public class Development extends BranchCatalog {

    private static final String SUB_DIR = "/dev";
    private final static String PROP_JVM_DESIGNER = "jvmDesigner";

    public Development(EntityRef owner) {
        this(owner, "title");
    }

    public Development(EntityRef owner, String PID) {
        super(owner, ImageUtils.getByPath("/images/development.png"), PID, null);
        model.addUserProp(PROP_JVM_DESIGNER, new ArrStr("-Xmx6G"), false, Access.Select);
    }

    @SuppressWarnings("unchecked")
    public final List<String> getJvmDesigner() {
        return (List<String>) model.getValue(PROP_JVM_DESIGNER);
    }

    @Override
    protected boolean isAutoGenerated() {
        return true;
    }

    @Override
    public Class<? extends Entity> getChildClass() {
        return Offshoot.class;
    }

    @Override
    String getSubDirectory() {
        return SUB_DIR;
    }

    @Override
    public boolean allowModifyChild() {
        return false;
    }

    Repository getRepository() {
        return (Repository) this.getOwner();
    }

}
